"""v0.911122

Revision ID: 5488f1dfb78a
Revises: a85e8b0d8f39
Create Date: 2023-04-21 14:47:32.964463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5488f1dfb78a'
down_revision = 'a85e8b0d8f39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
