"""v0.91112

Revision ID: a85e8b0d8f39
Revises: 48680669a529
Create Date: 2023-04-21 14:42:31.444335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85e8b0d8f39'
down_revision = '48680669a529'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
